Repository Zack-Dx/Discord-clone-project, pull requests merged in 2022-10, with the labels that each got.

#9 added the new section
  css/style.css
  img/container5.svg
  index.html
Labels: enhancement, hacktober, hacktober accepted

#10 Added Footer Section
  css/style.css
  img/Flag-logo.png
  img/discord-logo.png
  img/facebook-svg.svg
  img/instagram-svg.svg
  img/twitter-svg.svg
  img/youtube-svg.svg
  index.html
Labels: enhancement, hacktober, hacktober accepted, Clean code

#14 Fixing some typos in footer
  css/style.css
  index.html
Labels: good first issue, hacktober, hacktober accepted

#18 Add animation in Landing Page
  css/style.css
  index.html
Labels: enhancement, hacktober, hacktober accepted, Clean code

#24 added OS recognition on download button
  css/style.css
  index.html
  js/script.js
Labels: hacktober, hacktober accepted, Clean code

#34 Solved the download icon issue
  css/style.css
  index.html
Labels: enhancement, hacktober, hacktober accepted, Clean code

#41 Add .gitignore and updated Readme
  .gitignore
  README.md
  img/mockup.jpg
Labels: documentation, hacktober, hacktober accepted, Clean code

#44 added social media links in footer instead of pic
  css/style.css
  index.html
Labels: enhancement, good first issue, hacktober, hacktober accepted

#55 Added hovering effects and links to the buttons #51
  css/style.css
  index.html
Labels: hacktober, hacktober accepted

#39 Added Dark Mode Toogle
  css/style.css
  index.html
  js/script.js
Labels: enhancement, hacktober, hacktober accepted

#135 #123 Issue fixed
  css/responsive.css
  index.html
Labels: hacktober, hacktober-accepted, hacktoberfest 2022

#156 Issue 134 Responsive Download
  css/responsive.css
  css/style.css
  download.html
  js/downloadScript.js
Labels: hacktober, hacktober-accepted, hacktoberfest 2022

#158 Created and Added Discord Nitro page
  Nitro.html
  img/nitrobg.png
  index.html
  nitro/assets/css/styles.css
  nitro/assets/css/styles.css.map
  nitro/assets/fonts/whitneybold.woff
  nitro/assets/fonts/whitneybook.woff
  nitro/assets/fonts/whitneylight.woff
  nitro/assets/images/background_video.mp4
  nitro/assets/images/background_video.webm
  nitro/assets/images/emoji_card.svg
  nitro/assets/images/favicon.ico
  nitro/assets/images/flag.png
  nitro/assets/images/nitro.svg
  nitro/assets/images/nitro_classic.svg
  nitro/assets/images/profile_card.svg
  nitro/assets/images/rep_card.svg
  nitro/assets/images/support_card.svg
  nitro/assets/images/uploads_card.png
  nitro/assets/images/video_card.png
  nitro/assets/images/wumpus.png
  nitro/assets/js/app.js
  nitro/assets/scss/abstracts/_fonts.scss
  nitro/assets/scss/abstracts/_index.scss
  nitro/assets/scss/abstracts/_variables.scss
  nitro/assets/scss/base/_index.scss
  nitro/assets/scss/base/_reset.scss
  nitro/assets/scss/base/_typography.scss
  nitro/assets/scss/components/_buttons.scss
  nitro/assets/scss/components/_container.scss
  nitro/assets/scss/components/_index.scss
  nitro/assets/scss/layout/_benefits.scss
  nitro/assets/scss/layout/_footer.scss
  nitro/assets/scss/layout/_header.scss
  nitro/assets/scss/layout/_index.scss
  nitro/assets/scss/layout/_nitro-classic.scss
  nitro/assets/scss/layout/_showcase.scss
  nitro/assets/scss/styles.scss
Labels: enhancement, hacktober, hacktober-accepted, hacktoberfest 2022, urgent, on hold
